# Generated by Django 3.2.9 on 2022-03-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20220320_0453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itembasketororder',
            name='user',
        ),
        migrations.AlterField(
            model_name='itembasketororder',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Кол-во шт товара'),
        ),
    ]
