# Generated by Django 3.2.9 on 2022-03-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0003_alter_favorite_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='user_anonimus',
            field=models.IntegerField(default=-1, editable=False),
        ),
    ]
