# Generated by Django 3.2.9 on 2022-03-19 19:05

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категории товаров',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='ColorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None)),
                ('description', models.TextField(verbose_name='Описание для админ панели')),
            ],
            options={
                'verbose_name': 'Цвета товаров',
                'verbose_name_plural': 'Цвета товаров',
            },
        ),
        migrations.CreateModel(
            name='SizeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_size', models.CharField(max_length=4, verbose_name='Тип размера (XXS,XS и т.д)')),
            ],
            options={
                'verbose_name': 'Размер товара',
                'verbose_name_plural': 'Размер',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=300, verbose_name='Название товара')),
                ('composition', models.TextField(blank=True, null=True, verbose_name='Состав (Не обязательно)')),
                ('growth_model', models.IntegerField(blank=True, null=True, verbose_name='Рост модели(Не обязательно)')),
                ('croi_model', models.IntegerField(blank=True, null=True, verbose_name='Крой (Не обязательно)')),
                ('season', models.CharField(blank=True, choices=[('all', 'круглогодичный'), ('demseason', ':демисезон'), ('summer', 'летний'), ('winter', 'зимний')], max_length=50, null=True, verbose_name='Сезон одежды (Не обязательно)')),
                ('dlc_detals', models.TextField(blank=True, null=True, verbose_name='Дополнительные детали (Не обязательно)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание товара (Не обязательно)')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('discount', models.IntegerField(default=0, verbose_name='Цена со скидкой')),
                ('is_discount', models.BooleanField(default=False, verbose_name='Цена по скидке?')),
                ('is_public', models.BooleanField(default=True, verbose_name='Опубликован?')),
                ('avatar', models.ImageField(blank=True, default='sys/employee_avatars/default.png', upload_to='sys/employee_avatars/', verbose_name='Превью товара')),
                ('avatar_small', models.ImageField(blank=True, default='sys/employee_avatars/default.png', editable=False, upload_to='sys/employee_avatars/', verbose_name='Маленькое превью товара')),
                ('cropping', image_cropping.fields.ImageRatioField('avatar', '270x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Маленькая Аватар сотрудника')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='product.categoryproduct', verbose_name='Категория товара')),
                ('colors', models.ManyToManyField(related_name='colors', to='product.ColorProduct', verbose_name='Цвета товара')),
                ('size_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_model', to='product.sizeproduct', verbose_name='Размер на модели(Не обязательно)')),
                ('sizes', models.ManyToManyField(related_name='sizes', to='product.SizeProduct', verbose_name='Размеры товара')),
            ],
            options={
                'verbose_name': 'Товары',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ImageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='sys/employee_avatars/default.png', editable=False, help_text='Автоматически добавляется при добавление основого, вы можете изменить его', upload_to='sys/employee_avatars/', verbose_name='Маленькая Аватар сотрудника')),
                ('cropping', image_cropping.fields.ImageRatioField('avatar', '270x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Маленькая Аватар сотрудника')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_set', to='product.product')),
            ],
            options={
                'verbose_name': 'Фото товара',
                'verbose_name_plural': 'Фото товара',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_text', models.CharField(max_length=3, verbose_name='Лейбл на товаре (Хит,10%,20% и т.д)')),
                ('discount_price', models.IntegerField(help_text='Сумма товаров снижается на указанный процент', verbose_name='Скидка в процентах')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('discounts', models.ManyToManyField(related_name='discounts', to='product.Product', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Система скидок',
                'verbose_name_plural': 'Система скидок',
            },
        ),
    ]
