# Generated by Django 3.2.9 on 2022-03-19 19:42

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220320_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageitem',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '270x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='Маленькая Аватар сотрудника'),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='image',
            field=models.ImageField(blank=True, default='sys/employee_avatars/default.png', help_text='Автоматически добавляется при добавление основого, вы можете изменить его', upload_to='sys/employee_avatars/', verbose_name='Маленькая Аватар сотрудника'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('avatar', '270x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='Маленькое превью товара'),
        ),
    ]
