# Generated by Django 3.2.9 on 2022-03-19 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=300, null=True, verbose_name='Область/край')),
                ('tower', models.CharField(blank=True, max_length=300, null=True, verbose_name='Населённый пункт')),
                ('street', models.CharField(blank=True, max_length=300, null=True, verbose_name='Улица')),
                ('number_house', models.IntegerField(blank=True, null=True, verbose_name='Номер дома')),
                ('number_flat', models.IntegerField(blank=True, null=True, verbose_name='Номер квартиры')),
                ('index_mail', models.IntegerField(blank=True, null=True, verbose_name='Индекс')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
