# Generated by Django 3.2.9 on 2022-03-19 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryadress',
            options={'verbose_name': 'Доставка', 'verbose_name_plural': 'Доставка'},
        ),
    ]
