# Generated by Django 3.2.9 on 2022-03-19 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorize', '0002_auto_20220313_2204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryAdress',
        ),
    ]
