# Generated by Django 3.2.9 on 2022-03-19 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorize', '0003_delete_deliveryadress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профиль'},
        ),
    ]
