# Generated by Django 3.2.9 on 2021-12-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Заголовок категории')),
            ],
            options={
                'verbose_name': 'Категории доп страниц',
                'verbose_name_plural': 'Категории страниц',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Адресс страницы транскриптом')),
                ('title', models.TextField(verbose_name='Заголовок статьи')),
                ('description', models.TextField(help_text='Первый абзац статьи.', verbose_name='Описание')),
                ('image', models.ImageField(blank=True, help_text='Будет отображаться в статье и в ее миниатюре в списке статей.', upload_to='sys/article_images/', verbose_name='Изображение статьи')),
                ('image_description', models.TextField(blank=True, max_length=400, verbose_name='Описание изображение статьи')),
                ('information_markdown', models.TextField(help_text='Поддерживает markdown.', verbose_name='Основная информация')),
                ('information_html', models.TextField(editable=False)),
                ('show_on_main', models.BooleanField(default=False, verbose_name='Страница в меню')),
                ('show_on_website', models.BooleanField(default=False, verbose_name='Опубликовано?')),
                ('category', models.ManyToManyField(blank=True, related_name='pages', to='pages.Category', verbose_name='Превью для главной')),
            ],
            options={
                'verbose_name': 'Шаблонная страница',
                'verbose_name_plural': 'Страница',
            },
        ),
    ]
